export const engCapitalize: string[] = [
    "A", "About", "Above", "After", "Again", "Against", "All", "Am", "An", "And",
    "Any", "Are", "As", "At", "Be", "Because", "Been", "Before", "Being", "Below",
    "Between", "Both", "But", "By", "Can", "Could", "Did", "Do", "Does", "Each",
    "Few", "For", "From", "Further", "Had", "Has", "Have", "He", "Her", "Here",
    "Him", "His", "How", "I", "If", "In", "Into", "Is", "It", "Its",
    "Just", "Like", "Little", "Make", "Man", "May", "Me", "Might", "More", "Most",
    "My", "Need", "No", "Not", "Of", "On", "Once", "One", "Only", "Or",
    "Other", "Our", "Out", "Over", "Own", "Said", "Same", "See", "She", "Should",
    "So", "Some", "Such", "Take", "Than", "That", "The", "Their", "Them", "Then",
    "There", "These", "They", "This", "Those", "Through", "To", "Too", "Under", "Until",
    "Up", "Use", "Very", "Was", "Way", "We", "Were", "What", "When", "Where",
    "Which", "Who", "Will", "With", "Would", "Yes", "You", "Your", "Abandon", "Abduct",
    "Abhor", "Abide", "Accept", "Accompany", "Accomplish", "Accuse", "Achieve", "Acquire",
    "Act", "Adapt", "Add", "Admire", "Advise", "Affect", "Agree", "Allow", "Analyze",
    "Apply", "Argue", "Arrive", "Ask", "Attach", "Attempt", "Attract", "Avoid", "Begin",
    "Believe", "Belong", "Break", "Bring", "Build", "Burn", "Call", "Carry", "Change",
    "Choose", "Claim", "Clear", "Climb", "Come", "Compare", "Complain", "Complete",
    "Connect", "Consider", "Construct", "Contain", "Continue", "Create", "Decide",
    "Deliver", "Demand", "Describe", "Design", "Develop", "Discover", "Discuss", "Do",
    "Draw", "Dream", "Drive", "Eat", "Enable", "Encourage", "End", "Enjoy",
    "Establish", "Evaluate", "Exchange", "Expect", "Explain", "Explore", "Fail", "Find",
    "Follow", "Forget", "Forgive", "Gain", "Get", "Give", "Go", "Grow", "Guess",
    "Handle", "Have", "Hear", "Help", "Hide", "Hope", "Imagine", "Improve", "Include",
    "Increase", "Inspire", "Instruct", "Interact", "Introduce", "Invest", "Invite", "Join",
    "Judge", "Keep", "Know", "Lead", "Learn", "Leave", "Let", "Listen", "Look",
    "Make", "Manage", "Meet", "Melt", "Move", "Need", "Observe", "Offer", "Open",
    "Organize", "Participate", "Pay", "Play", "Prepare", "Present", "Produce",
    "Promote", "Protect", "Provide", "Pursue", "Question", "Quote", "Read", "Realize",
    "Recommend", "Reflect", "Refuse", "Regard", "Relate", "Remember", "Remind", "Report",
    "Respond", "Reveal", "Run", "Say", "See", "Sell", "Send", "Serve", "Set", "Share",
    "Show", "Simplify", "Speak", "Spend", "Stand", "Start", "Stay", "Study", "Suggest",
    "Support", "Take", "Talk", "Teach", "Tell", "Test", "Think", "Touch", "Trade",
    "Train", "Transfer", "Transform", "Trust", "Try", "Turn", "Understand", "Use",
    "Value", "Wait", "Want", "Watch", "Win", "Wish", "Work", "Write", "Yell", "Zoom",
    "Abundant", "Adventurous", "Ancient", "Anxious", "Beautiful", "Brave", "Bright",
    "Calm", "Charming", "Cheerful", "Courageous", "Creative", "Curious", "Daring",
    "Eager", "Elegant", "Energetic", "Exciting", "Fabulous", "Faithful", "Fearless",
    "Friendly", "Generous", "Gentle", "Grateful", "Happy", "Hopeful", "Humble",
    "Imaginative", "Incredible", "Intelligent", "Joyful", "Kind", "Lovable", "Magical",
    "Mindful", "Motivated", "Noble", "Optimistic", "Passionate", "Peaceful", "Playful",
    "Radiant", "Reliable", "Respectful", "Sincere", "Spirited", "Strong", "Thoughtful",
    "Trustworthy", "Vibrant", "Warm", "Wise", "Young", "Zealous", "Absent", "Acceptable",
    "Accessible", "Adaptable", "Ambitious", "Appreciative", "Assertive", "Attentive",
    "Authentic", "Automatic", "Available", "Believable", "Beneficial", "Careful",
    "Charismatic", "Compassionate", "Comprehensive", "Confident", "Conscientious",
    "Consistent", "Constructive", "Contemplative", "Creative", "Cynical", "Delicate",
    "Diligent", "Discrete", "Efficient", "Enthusiastic", "Exemplary", "Extraordinary",
    "Flexible", "Forgiving", "Graceful", "Genuine", "Helpful", "Impartial", "Inquisitive",
    "Inspiring", "Intuitive", "Judicious", "Lively", "Logical", "Objective", "Passionate",
    "Peace", "Persistent", "Practical", "Proactive", "Productive", "Realistic",
    "Reflective", "Resourceful", "Sensible", "Supportive", "Sympathetic", "Tactful",
    "Thoughtful", "Thorough", "Tolerant", "Unbiased", "Vigilant", "Witty", "Yearning",
    "Zealful"
];


export const engNonCapitalized: string[] = [
    "a", "about", "above", "after", "again", "against", "all", "am", "an", "and",
    "any", "are", "as", "at", "be", "because", "been", "before", "being", "below",
    "between", "both", "but", "by", "can", "could", "did", "do", "does", "each",
    "few", "for", "from", "further", "had", "has", "have", "he", "her", "here",
    "him", "his", "how", "i", "if", "in", "into", "is", "it", "its",
    "just", "like", "little", "make", "man", "may", "me", "might", "more", "most",
    "my", "need", "no", "not", "of", "on", "once", "one", "only", "or",
    "other", "our", "out", "over", "own", "said", "same", "see", "she", "should",
    "so", "some", "such", "take", "than", "that", "the", "their", "them", "then",
    "there", "these", "they", "this", "those", "through", "to", "too", "under", "until",
    "up", "use", "very", "was", "way", "we", "were", "what", "when", "where",
    "which", "who", "will", "with", "would", "yes", "you", "your", "abandon", "abduct",
    "abhor", "abide", "accept", "accompany", "accomplish", "accuse", "achieve", "acquire",
    "act", "adapt", "add", "admire", "advise", "affect", "agree", "allow", "analyze",
    "apply", "argue", "arrive", "ask", "attach", "attempt", "attract", "avoid", "begin",
    "believe", "belong", "break", "bring", "build", "burn", "call", "carry", "change",
    "choose", "claim", "clear", "climb", "come", "compare", "complain", "complete",
    "connect", "consider", "construct", "contain", "continue", "create", "decide",
    "deliver", "demand", "describe", "design", "develop", "discover", "discuss", "do",
    "draw", "dream", "drive", "eat", "enable", "encourage", "end", "enjoy",
    "establish", "evaluate", "exchange", "expect", "explain", "explore", "fail", "find",
    "follow", "forget", "forgive", "gain", "get", "give", "go", "grow", "guess",
    "handle", "have", "hear", "help", "hide", "hope", "imagine", "improve", "include",
    "increase", "inspire", "instruct", "interact", "introduce", "invest", "invite", "join",
    "judge", "keep", "know", "lead", "learn", "leave", "let", "listen", "look",
    "make", "manage", "meet", "melt", "move", "need", "observe", "offer", "open",
    "organize", "participate", "pay", "play", "prepare", "present", "produce",
    "promote", "protect", "provide", "pursue", "question", "quote", "read", "realize",
    "recommend", "reflect", "refuse", "regard", "relate", "remember", "remind", "report",
    "respond", "reveal", "run", "say", "see", "sell", "send", "serve", "set", "share",
    "show", "simplify", "speak", "spend", "stand", "start", "stay", "study", "suggest",
    "support", "take", "talk", "teach", "tell", "test", "think", "touch", "trade",
    "train", "transfer", "transform", "trust", "try", "turn", "understand", "use",
    "value", "wait", "want", "watch", "win", "wish", "work", "write", "yell", "zoom",
    "abundant", "adventurous", "ancient", "anxious", "beautiful", "brave", "bright",
    "calm", "charming", "cheerful", "courageous", "creative", "curious", "daring",
    "eager", "elegant", "energetic", "exciting", "fabulous", "faithful", "fearless",
    "friendly", "generous", "gentle", "grateful", "happy", "hopeful", "humble",
    "imaginative", "incredible", "intelligent", "joyful", "kind", "lovable", "magical",
    "mindful", "motivated", "noble", "optimistic", "passionate", "peaceful", "playful",
    "radiant", "reliable", "respectful", "sincere", "spirited", "strong", "thoughtful",
    "trustworthy", "vibrant", "warm", "wise", "young", "zealous", "absent", "acceptable",
    "accessible", "adaptable", "ambitious", "appreciative", "assertive", "attentive",
    "authentic", "automatic", "available", "believable", "beneficial", "careful",
    "charismatic", "compassionate", "comprehensive", "confident", "conscientious",
    "consistent", "constructive", "contemplative", "creative", "cynical", "delicate",
    "diligent", "discrete", "efficient", "enthusiastic", "exemplary", "extraordinary",
    "flexible", "forgiving", "graceful", "genuine", "helpful", "impartial", "inquisitive",
    "inspiring", "intuitive", "judicious", "lively", "logical", "objective", "passionate",
    "peace", "persistent", "practical", "proactive", "productive", "realistic",
    "reflective", "resourceful", "sensible", "supportive", "sympathetic", "tactful",
    "thoughtful", "thorough", "tolerant", "unbiased", "vigilant", "witty", "yearning",
    "zealful"
];
